---
- name: call sqlplus
  hosts: "{{ hosts_name }}"

  tasks:
    - name: init folder
      file:
        path: "/OracalAutoDB/{{ project }}/"
        state: absent
      file:
        path: "/OracalAutoDB/{{ project }}/"
        state: directory
