---
- name: call sql*plus
  hosts: "{{ hosts_name }}"

  tasks:
    - name: init folder(delete folder)
      file:
        path: "{{ work_path }}/{{ project }}/"
        state: absent
    - name: init folder(create folder)
      file:
        path: "{{ work_path }}/{{ project }}/"
        state: directory
        
    - name: get .sql files(git clone)
      git:
        repo: "https://github.com/purelydinkum/{{ project }}"
        dest: "{{ work_path }}/{{ project }}"
        clone: yes
        version: "{{ branch }}"
        
#- name: chmod .sql files
  #file:
    #dest: "{{ work_path }}/{{ project }}/"
    #mode: '0755'
    #state: directory
    #recurse : no
    
    - name: chmod .sql files
      shell:
        chdir: "{{ work_path }}/{{ project }}/"
        cmd: chmod 755 *
        
    - name: recurse .sql file add "/"
      debug:
        msg: lineinfile
     
    - name: call sqlplus
      debug:
        msg: echo /tmp/testgit/aaa.sql |.\sqlplus.exe "{{ DB_AC }}/{{ DB_PW }}@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host={{ DB_HOST }})(Port={{ DB_PORT }}))(CONNECT_DATA=(SID={{ DB_SID }})))" as {{ DB_ROLE }}
        #cammand:echo /tmp/testgit/aaa.sql |.\sqlplus.exe "{{ DB_AC }}/{{ DB_PW }}@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host={{ DB_HOST }})(Port={{ DB_PORT }}))(CONNECT_DATA=(SID={{ DB_SID }})))" as {{ DB_ROLE }}

    - name: return log
      debug:
        msg: return log
