---
- name: call sqlplus
  hosts: "{{ hosts_name }}"

  tasks:
    - name: init folder(delete folder)
      file:
        path: "/OracalAutoDB/{{ project }}/"
        state: absent
    - name: init folder(create folder)
      file:
        path: "/OracalAutoDB/{{ project }}/"
        state: directory
    - name: git clone
      git:
        repo: "https://github.com/purelydinkum/{{ project }}"
        dest: "/OracalAutoDB/{{ project }}"
        clone: yes
        version: "{{ branch }}"
