---
- name: File Sync
  hosts: all

  tasks:
    - name: Git Clone from the jump server
      shell:
       cmd: |
        . ~/.bash_profile;
        mkdir -p tmp
        echo testttt > tmp/test_ansible.txt
      when: "{{ inventory_hostname == '172.17.12.24' }}"
