---
- name: File Sync
  hosts: all

  tasks:
    - name: Git Clone from the jump server
      shell:
       cmd: |
        . ~/.bash_profile;
        mkdir -p tmp
        echo testttt > tmp/test_ansible.txt
        echo testttt > tmp/test_ansible2.txt
        echo testttt > tmp/test_ansible3.txt
      when: "{{ inventory_hostname == '172.17.12.24' }}"
       
    - name: Fetch the file from the jump server to ansible master 
      fetch: src=tmp/* dest=buffer/ flat=yes
      when: "{{ inventory_hostname == '172.17.12.24' }}"

    - name: Copy the file from ansible master to target server
      copy: src=buffer/test_ansible.txt dest=/tmp/
      when: "{{ inventory_hostname != '172.17.12.24' }}"
