---
- name: DB_Deploy
  hosts: 172.16.14.141

  tasks:
    - name: call python
      shell:
       cmd: |
         . ~/.bash_profile;
         echo /opt/sqldepoly/MSSQLDepoly.py --num \"{{ num }}\" --key {{ key }} --env {{ env }} --projname {{ projname }} --Log_Name {{ Jenkins_Base_Id_Name }}_{{  tower_job_template_name  }}_{{  tower_job_id  }} --serverip {{ db_cicd_mssql_host }} --port {{ db_cicd_mssql_port }} --dbuser {{ db_cicd_mssql_username }} --dbpasswd {{ db_cicd_mssql_password }} --database {{ db_cicd_mssql_database }} --encoding utf-8;
         /opt/sqldepoly/MSSQLDepoly.py --num \"{{ num }}\" --key {{ key }} --env {{ env }} --projname {{ projname }} --Log_Name {{ Jenkins_Base_Id_Name }}_{{  tower_job_template_name  }}_{{  tower_job_id  }} --serverip {{ db_cicd_mssql_host }} --port {{ db_cicd_mssql_port }} --dbuser {{ db_cicd_mssql_username }} --dbpasswd {{ db_cicd_mssql_password }} --database {{ db_cicd_mssql_database }} --encoding utf-8;