---
- name: DB_Deploy
  hosts: all

  tasks:
    - name: call python
      ignore_errors: True
      no_log: False
      register: r_python
      shell:
       cmd: |
         . ~/.bash_profile;
         #echo /opt/sqldepoly/ORACLEDepoly.py --num '{{ num }}' --key {{ key }} --projname {{ projname }} --env {{ env }} --timestamp {{ timestamp }} --Log_Name {{ Jenkins_Base_Id_Name }}_{{ tower_job_template_name }}_{{ tower_job_id }} --serverip {{ db_cicd_oracle_host }} --port {{ db_cicd_oracle_port }} --dbuser {{ db_cicd_oracle_username }} --dbpasswd '{{ db_cicd_oracle_password }}' --dbdsn {{ db_cicd_oracle_sid }} --encoding utf-8;
         /opt/sqldepoly/ORACLEDepoly.py --num '{{ num }}' --key {{ key }} --projname {{ projname }} --env {{ env }} --timestamp {{ timestamp }}  --Log_Name {{ Jenkins_Base_Id_Name }}_{{ tower_job_template_name }}_{{ tower_job_id }} --serverip {{ db_cicd_oracle_host }} --port {{ db_cicd_oracle_port }} --dbuser {{ db_cicd_oracle_username }} --dbpasswd '{{ db_cicd_oracle_password }}' --dbdsn {{ db_cicd_oracle_sid }} --encoding utf-8;
    - name: python standard msg
      debug: 
        msg: "{{ r_python.msg | default('',true) }}"
    - name: python standard out
      debug: 
        msg: "{{ r_python.stdout_lines | default('',true) }}"
    - name: python standard error
      debug:
        msg: "{{ r_python.stderr_lines | default('',true) }}"
    - fail:
        msg: "Error shell, please check the debug messages."
      when: r_python.rc != 0