---
- name: DB_Deploy
  hosts: 172.16.14.141

  tasks:
    - name: call python
      shell:
       cmd: |
         . ~/.bash_profile;
         echo --ticket_number_path {{ ticket_number_path }} --projname {{ projname }} --Log_Name {{ Jenkins_Base_Id_Name }}_{{  tower_job_template_name  }}_{{  tower_job_id  }} --dbtype ORACLE --serverip {{ db_cicd_oracle_host }} --port {{ db_cicd_oracle_port }} --dbuser {{ db_cicd_oracle_username }} --dbpasswd {{ db_cicd_oracle_password }} --dbdsn {{ db_cicd_oracle_sid }} --encoding utf-8;
         /opt/sqldepoly/ORACLEDepoly.py --ticket_number_path {{ ticket_number_path }} --projname {{ projname }} --Log_Name {{ Jenkins_Base_Id_Name }}_{{  tower_job_template_name  }}_{{  tower_job_id  }} --serverip {{ db_cicd_oracle_host }} --port {{ db_cicd_oracle_port }} --dbuser {{ db_cicd_oracle_username }} --dbpasswd {{ db_cicd_oracle_password }} --dbdsn {{ db_cicd_oracle_sid }} --encoding utf-8;