---
- name: DB_Deploy
  hosts: 172.16.14.141

  tasks:
    - name: call python
      ignore_errors: True
      no_log: True
      register: r_python
      shell:
       cmd: |
         . ~/.bash_profile;
         /tmp/test.sh;
    - name: python standard msg
      debug: 
        msg: '{{ r_python.msg }}'
      when: r_python.msg != None
    - name: python standard out
      debug: 
        msg: '{{ r_python.stdout_lines }}'
      when: r_python.stdout_lines != None
    - name: python standard error
      debug:
        msg: '{{ r_python.stderr_lines }}'
      when: r_python.stderr_lines != None
    - fail:
        msg: "Error shell, please check the debug messages."
      when: r_python.rc != 0