---
- name: DB_Deploy
  hosts: 172.16.14.141

  tasks:
    - name: call python
      ignore_errors: True
      no_log: True
      register: r_python
      shell:
       cmd: |
         . ~/.bash_profile;
         /tmp/test.sh;