---
- name: DB_Deploy
  hosts: 172.16.14.141

  tasks:
    - name: call python
      ignore_errors: True
      no_log: True
      register: r_python
      shell:
       cmd: |
         . ~/.bash_profile;
         /tmp/test.sh;
    - name: python Standard Out
      debug:
        msg: '{{ r_python.stdout }}'
      when: r_python.stdout != ""
    - name: python Standard Error
      debug:
        msg: '{{ r_python.stderr }}'
      when: r_python.stderr != ""
    - fail:
        msg: "error shell, Please check the debug messages."
      when: r_python.stderr != ""