---
- name: testeeeee
  hosts: '{{ hosts_name }}'
  no_log: true

  tasks:
    - name: test
      no_log: false
      shell: 
        cmd: echo '{{ DB_PW }}' > /tmp/teste
    - name: test2
      no_log: false
      shell: 
        cmd: echo '{{ TEST_PW }}' > /tmp/TEST_PW
