---
- name: DB_Deploy
  hosts: 172.16.14.141

  tasks:
    - name: call python
      ignore_errors: True
      no_log: True
      register: r_python
      shell:
       cmd: |
         . ~/.bash_profile;
         /tmp/test.sh;
    - debug:
        msg: 'Standard Out:{{ r_python.stdout }}'
      when: r_python.stdout != ""
    - debug:
        msg: 'Standard Error:{{ r_python.stderr }}'
      when: r_python.stderr != ""
    - fail:
        msg: "error shell."
      when: r_python.stderr != ""