---
- name: test
  hosts: 172.16.11.242 

  tasks:
  - name: Touch the same file, but add/remove some permissions
    file:
      path: /tmp/tomtest/aaa
      state: touch
      mode: u+rw,g-wx,o-rwx
